[versions]
agp = "9.0.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.13.0"
constraintlayout = "2.2.1"
securityCrypto = "1.1.0-alpha06"
fragment = "1.8.9"
recyclerview = "1.4.0"
swiperefreshlayout = "1.1.0"
zxing = "3.5.3"
iconics = "5.5.0"
communityMaterial = "7.0.96.1-kotlin"
viewpager2 = "1.1.0"
okhttp = "4.12.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }
fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
zxing = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
iconics-core = { group = "com.mikepenz", name = "iconics-core", version.ref = "iconics" }
iconics-views = { group = "com.mikepenz", name = "iconics-views", version.ref = "iconics" }
community-material-typeface = { group = "com.mikepenz", name = "community-material-typeface", version.ref = "communityMaterial" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-jvm = { group = "com.squareup.okhttp3", name = "okhttp-urlconnection", version.ref = "okhttp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

